### ISSUE TITLE
Population parameters are parsed correctly only if marked as free parameters in data generation template

### ISSUE THREAD

**Issue by mronkko** [simsem/simsem#34]
I start with a test case  and then explain the issue below:

```
library(simsem)

loading <- matrix(0, 6, 2)
loading[1:3, 1] <- .7
loading[4:6, 2] <- .7
LY <- bind(loading)

latent.cor <- matrix(.5, 2, 2)
diag(latent.cor) <- 1
RPS <- binds(latent.cor)

RTE <- binds(diag(6))

CFA.Model <- model(LY = LY, RPS = RPS, RTE = RTE, modelType = "CFA")

Output <- sim(10, model = "f1 =~ y1 + y2 + y3
              f2 =~ y4 + y5 + y6", n=200, generate = CFA.Model,
              lavaanfun = "cfa", std.lv = TRUE)

summary(Output)
```

Here I am generating data from a SimSem template, which determines only the population model, but not the estimated model and then estimate the same model specified with lavaan syntax. (This follows the first example on the simsem website.) The estimated model is identical to the population model. Nevertheless, I get the following error:

```
NOTE: The data generation model is not the same as the analysis model. See the summary of the population underlying data generation by the summaryPopulation function.
```

summaryPopulation gives the following
```
                 y1~~y1 y2~~y2 y3~~y3 y4~~y4 y5~~y5 y6~~y6 y1~1 y2~1 y3~1 y4~1 y5~1 y6~1
Population Value 0.51   0.51   0.51   0.51   0.51   0.51   0    0    0    0    0    0   
```

I would instead expect simsem to list the actual population values of all parameters instead of just those that were declared as free parameters in the SimSem template used to generate the data.

**Comment by psunthud** [comment]
This is actually our designs to save parameter values for only free parameters. In the CFA.Model, you have all fixed parameters except measurement error variances which are free by default. Therefore, summaryPopulation only shows measurement error variances and item intercepts. If you change the codes as follows, the code will run as expected.

    loading <- matrix(0, 6, 2)
    loading[1:3, 1] <- NA
    loading[4:6, 2] <- NA
    LY <- bind(loading, .7)

    latent.cor <- matrix(NA, 2, 2)
    diag(latent.cor) <- 1
    RPS <- binds(latent.cor, .5)

    RTE <- binds(diag(6))

    CFA.Model <- model(LY = LY, RPS = RPS, RTE = RTE, modelType = "CFA")

    Output <- sim(10, model = "f1 =~ y1 + y2 + y3\nf2 =~ y4 + y5 + y6", n=200, generate = CFA.Model,     lavaanfun = "cfa", std.lv = TRUE)

    summary(Output)

**Comment by mronkko** [comment]
This is not a very intuitive design. A population does not have free parameters but all parameters are fixed. How the population parameters are printed out should not depend on the model that is estimated because the estimated model and population model are two different things.

**Comment by t129j179** [comment]
But the point of a simulation is not to check that the fixed values in your analysis model match the fixed values in your population (i.e., bias of fixed parameters).  The number of all possible model parameters grows geometrically with the number of observed variables (dimensions of theta, tau, and rows of lambda) and latent variables (dimensions of psi, beta, and columns of lambda).  It just wouldn't make sense to store so many structural zeros (and some ones) because the results object would become too large.  The `paramValue` slot in the `SimResult` object is simply organized in such a way that facilitates calculating bias, etc., for corresponding parameters in the population and analysis models.

You can see your population parameters in the `SimSem` object: `CFA.Model@dgen`
And perhaps this is what you want `summaryPopulation()` to return.  Perhaps a solution would be to have two different methods for  `summaryPopulation()`.  When "object" is a `SimResult` object, it will behave as it does now.  But when "object" is a `SimSem` object, it could print the population matrices.  Something along the lines of:

`if (class(object) == "SimSem") {`
`  return(lapply(object@dgen, function(x) if (!is.null(x) ) x@popParam))`
`}`

Note that in Mikko's example above, this would return `NaNs` for empty matrices because he was only providing the first argument to `bind()`, which is "free", not "popParam".

**Comment by mronkko** [comment]
I am not proposing that structural zeros should be stored. What I would like to see is that the non-zero population parameters are stored regardless of what model is being estimated.

 In the example above, my estimated model is exactly the same as the population model, yet SimSem incorrectly gives a warning that this would not be the case. Also the documentation of summaryPopulation states that "Summarize the population model used for data generation underlying a result object". In my example it does not do that because the non-zero values of the loadings are not reported.
