### ISSUE TITLE
Plot models with semPlot?

### ISSUE THREAD

**Issue by jflournoy** [simsem/simsem#41]
This is a feature request. 

Plotting path diagrams with the semPlot package is very easy, but it requires lavaan syntax. Is it possible to have a function that converts any type of simsem model into lavaan syntax (for example, I specify the population model using simsem matrix format, and then export lavaan syntax for use in semPlot)?

**Comment by t129j179** [comment]
This might be a feature request for the semPlot package instead of simsem (i.e., if you want the semPaths() function to accept a simsem object as easily as a lavaan object).  But this is indeed pretty easy to do already.  The function you describe is actually not necessary, because lavaan itself actually converts model syntax into a parameter table, and simsem does the same thing with the parameter matrices.  When you create a simsem Model object using the model() function, that S4 object has a slot called "pt" (which stands for lavaan's "parameter table").  You can submit that parameter table to the semPaths() function to get a path diagram, optionally with parameter values.  Using the first example from the ?model help page:

`loading <- matrix(0, 6, 2)`
`loading[1:3, 1] <- NA`
`loading[4:6, 2] <- NA`
`LY <- bind(loading, 0.7)`
`latent.cor <- matrix(NA, 2, 2)`
`diag(latent.cor) <- 1`
`RPS <- binds(latent.cor, 0.5)`
`RTE <- binds(diag(6))`
`VY <- bind(rep(NA,6),2)`
`CFA.Model <- model(LY = LY, RPS = RPS, RTE = RTE, modelType = "CFA")`
`semPaths(CFA.Model@pt)`
`semPaths(CFA.Model@pt, what = "par")`

**Comment by t129j179** [comment]
FYI, you can also use that parameter table (CFA.Model@pt) in place of model syntax if you want to fit your analysis model using lavaan(), cfa(), or sem() functions, or simsem's analyze() function.
