### ISSUE TITLE
Cannot find inspect method

### ISSUE THREAD

**Issue by keithmarkus** [simsem/simsem#52]
Using simsem 0.5-13 I am unable to locate the inspect method for simsem output.  The example in the simsem::inspect help file produces the following error.

> inspect(Output, "se", improper = TRUE, nonconverged = TRUE)
Error in UseMethod("inspect", object) : 
  no applicable method for 'inspect' applied to an object of class "SimResult"

Likewise, methods() does not list an inspect method:
> methods(class = class(Output))
[1] anova        coef         summaryShort summary     
see '?methods' for accessing help and source code

> class(Output)
[1] "SimResult"
attr(,"package")
[1] "simsem"

**Comment by TDJorgensen** [comment]
Thanks, Keith.  I'm surprised this issue has never come up before.  I guess no one ever used `inspect()` on a `SimResult` object before.  I think the issue is that the `NAMESPACE` file imported lavaan's `inspect` method but did not export it along with the ones you see are available (e.g., `summary`, `coef`, `anova`).

I just updated the `NAMESPACE` file to export the `inspect` method, and the examples on the `?simsem::inspect` help page work without error.  If you want to install the latest version of simsem, it will require lavaan >= 0.6

```
install.packages("lavaan", repos="http://www.da.ugent.be", type="source")
devtools::install_github("simsem/simsem/simsem")
```
