### ISSUE TITLE
Calculate sample size needed for 80% power to detect indirect effect

### ISSUE THREAD

**Issue by isaactpetersen** [simsem/simsem#58]
I greatly appreciate your work on the `simsem` package.  I'd like to extend [Example 17](https://github.com/simsem/simsem/wiki/Example-17:-Select-a-set-of-variables-for-analysis) of the simsem documentation to estimate the sample size needed to have 80% power to detect an indirect effect from `F11` to `F33` via `F22`.  I'd like to use [`LISREL` syntax](https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version03/ex17/ex17.R).

The [`lavaan` syntax](https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version05/ex17/ex17.R) for this example seems easily extendable to to estimate the sample size needed to detect the indirect effect because it already estimates the indirect (mediation) effect:

```
med := con8 * con10
```

Thus, I can just randomly vary the `n=` argument in the `sim()` function, and then apply the `continuousPower()` function to the simulation result, as described [here](https://github.com/simsem/simsem/issues/55).  Doing this, I learn that the sample size needed to have 80% power to detect the indirect effect is 71:

```
output_lavaan <- sim(NULL, n = seq(from = 40, to = 300, by = 10), model = analyzeModel1, generate = popModel)
powerToDetectIndirectEffect <- continuousPower(output_lavaan, contN = TRUE, powerParam = c("med"))
round(powerToDetectIndirectEffect, 2)
```

Is it possible to similarly extend the [`LISREL` syntax](https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version03/ex17/ex17.R) for this example to to estimate the sample size needed to have 80% power to detect an indirect effect from `F11` to `F33` via `F22`?  Thanks!

**Comment by TDJorgensen** [comment]
LISREL matrices contain model parameters, not functions of model parameters.  That's why you need the lavaan syntax to specify user-defined functions of parameters.  

If you need to use LISREL matrices for some other reason, you can still use the `outfun=` argument to return a test significance of an indirect effect using some other method besides the delta method, which would not adequately control Type I errors at your lower Ns toward 40 anyway.  Try working through the help-page examples of `semTools::monteCarloMed()`, which returns a Monte Carlo CI for any function of parameters.  You do not need to specify user-defined parameters in your syntax that way; you only need to label the necessary parameters (labels can be used instead of `NA` to specify free parameters in LISREL matrices) so that you can define a function of those labels in `monteCarloMed()`.  You can write a custom function (like I showed you in #55) that checks whether the CI includes 0, then take the mean of those TRUE/FALSE values to estimate power.  

```
checkCI <- function(fit) {
  med <- "a*b"
  ## extract point and SE estimates from lavaan object
  myParams <- c("a","b") # replace with labels you used to define "med"
  myCoefs <- coef(fit)[myParams]
  myACM <- vcov(fit)[myParams, myParams]
  ## obtain CI
  level <- 95 #% confidence
  out <- semTools::monteCarloMed(med, myCoefs, ACM = myACM, plot = FALSE, CI = level)
  limits <- out[[paste0(level, "% Confidence Interval")]]
  ## test H0: a*b == 0
  all(sign(limits) == 1L) || all(sign(limits) == -1L) # either all negative or all positive
}
```

The caveat is that you would not be able to use `continuousPower()` to automatically estimate power at each N, or find the N with at least 80% estimated power.  But you can easily apply that method yourself.  When you save the TRUE/FALSE vector indicating whether each test was significant, also save your vector of Ns, then run the logistic regression yourself.

```
rej <- do.call(c, getExtraOutput(output_lavaan))
Ns <- seq(from = 40, to = 300, by = 10)
## N predicts rejecting H0
mod <- glm(rej ~ Ns, family = binomial(link = logit))
## calculate predicted probability of rejection at each N,
## with SEs to quantify uncertainty about power at each N
pred <- predict(mod, type = "response", se.fit = TRUE)
cbind(Ns, power = pred$fit, SE = pred$se.fit)
```

Note that you can increase the precision of your power estimates (to be more certain about the minimum required N) if you use more replications.
```
Ns <- sample(40:300, size = 500, replace = TRUE)
```

**Comment by isaactpetersen** [comment]
Great, thanks for this info!  I appreciate it.
