### ISSUE TITLE
What is the difference between the two simulation with real data approaches?

### ISSUE THREAD

**Issue by monamandala-l** [simsem/simsem#59]
```
loading <- matrix(0, 9, 3)
loading[1:3, 1] <- NA
loading[4:6, 2] <- NA
loading[7:9, 3] <- NA
cfamodel <- estmodel(LY=loading, modelType="CFA", indLab=paste("x", 1:9, sep=""))

out <- analyze(cfamodel, HolzingerSwineford1939)

datamodel.nomis <- model.lavaan(out, std=TRUE)

output.nomis <- sim(1000, n=nrow(HolzingerSwineford1939), datamodel.nomis)
summary(output.nomis)
```

and

```
HS.model <- ' visual  =~ x1 + x2 + x3
	              textual =~ x4 + x5 + x6
	              speed   =~ x7 + x8 + x9 '

fit <- cfa(HS.model, data=HolzingerSwineford1939)

output.nomis <- sim(1000, n=nrow(HolzingerSwineford1939), model = fit, generate = fit)
```

I am unsure of which to choose for sample size and power analysis for my data and model.

**Comment by TDJorgensen** [comment]
I can't tell what you are trying to do with 
```
output.nomis <- sim(1000, n=nrow(HolzingerSwineford1939), datamodel.nomis)
```
because you have not named the third argument.  The third argument to `sim()` is `n=`, but you already specified that as the second argument, so R will use `datamodel.nomis` for the second argument (`model=`).  Is that what you meant to do?  It would use the estimated parameters from the fitted model to generate data, then fit the same model to that data.

Conceptually, the second approach is the same, but you shouldn't pass a fitted model to `model=` or `generate=` (see the `?sim` help page for available options).  You could instead pass the parameter table to both arguments, but you only need to pass it to `model=` because that will also be used for data-generation if `generate=` is not specified.
```
output.nomis <- sim(1000, n = nrow(HolzingerSwineford1939), model = parTable(fit))
```

**Comment by monamandala-l** [comment]
Hi, 
thank you for the response.
The first example is from simsem Vignettes, I would assume the third argument in sim() function is the 'model=' argument.

If the two approaches are conceptually equal, then the second one definitely seems easier to apply.
However, when trying the suggested approach, I receive the error and assume that it is not applicable?:

<img width="684" alt="error" src="https://user-images.githubusercontent.com/58108270/69481279-98930f80-0e18-11ea-8bca-64579246e1f8.PNG">

**Comment by TDJorgensen** [comment]
Turns out that you could pass a fitted lavaan model after all.  It is not list on the help page, but Sunthud programmed a check for a `lavaan` object, and extracts the `parTable()` from it.  So that is why that [Vignette 7](https://github.com/simsem/simsem/blob/master/SupportingDocs/Examples/Version05/ex7/ex7.R) syntax works.

The reason the syntax I suggested (which the help page indicated was correct) did not work was that lavaan has since added some new names to its parameter table (`block` and `level`, related to the newer multilevel capabilities), so `sim`'s internal check did not recognize it as a lavaan parameter table.  That bug is now fixed in the development version:
```
devtools::install_github("simsem/simsem/simsem")
```
And I agree, this second option is easier for your situation.
