### ISSUE TITLE
Dataset generation

### ISSUE THREAD

**Issue by N34980** [simsem/simsem#63]
Hi,

I am trying to replicate the results of a couple of studies that used a similar generated dataset. Hence, the first step for me is to generate the same dataset.
These studies are:

Lin, G.-C., Wen, Z., Marsh, H., & Lin, H.-S. (2010). Structural equation models of latent interactions: Clarification of orthogonalizing and double-mean-centering strategies. Structural Equation Modeling: A Multidisciplinary Journal, 17(3), 374–391. https://doi.org/10.1080/10705511.2010.488999

Little, T. D., Bovaird, J. A., & Widaman, K. F. (2006). On the merits of orthogonalizing powered and product terms: Implications for modeling interactions among latent variables. Structural Equation Modeling: A Multidisciplinary Journal, 13(4), 497–519. https://doi.org/10.1207/s15328007sem1304_1

Marsh, H. W., Wen, Z., & Hau, K.-T. (2004). Structural equation models of latent interactions: Evaluation of alternative estimation strategies and indicator construction. Psychological Methods, 9(3), 275–300. https://doi.org/10.1037/1082-989X.9.3.275

I am copying-pasting the description of the simulated dataset by Lin et al. (2010):
```"The (simulated) population data were created from a model with Y~ 0.4*X1 + 0.4*X2 + 0.2 X1X2 where X1 and X2 were standardized variables, the variance of Y was 1, and the correlation coefficient between X1 and X2 was 0.3. The loadings relating each indicator to its first-order factor were all 0.7. X1 and X2 are simulated from the following four distribution conditions: N(0,1), chi2(16), chi2(8) and chi2(4). Except for N(0,1) the third-order moments of (X1,X2) are not zero. Like the Little et al. (2006) design, 1,000 replications were generated with sample size of 1,500 for each distribution condition."```

So... using Lavaan, I could specify the following model to generate data:

simdata <-'
X1 =~ .7*x11 + .7*x12 + .7*x13
X2 =~ .7*x21 + .7*x22 + .7*x23
Y =~ .7*y1 + .7*y2 + .7*y3
X1X2 =~ X1*X2
X1 ~~ .3*X2
Y ~ 0.4*X1 + 0.4*X2 + 0.2*X1X2'
generate(simdata, n = 1500, seed=1234)

However, my understanding is that factors cannot be multiplied in a lavaan script, which makes the previous specification incorrect. Am I right?
If so, how would you use simsem to generate the dataset used in these three articles?

Many thanks,

Roger

**Comment by TDJorgensen** [comment]
Your example syntax should be imbedded in backticks, otherwise the asterisks are interpreted as italics.

> However, my understanding is that factors cannot be multiplied in a lavaan script, which makes the previous specification incorrect. Am I right?

Yes, the syntax `X1X2 =~ X1*X2` is interpreted as labeling the loading `X1X2 =~X2` with the character `"X1"`.  The colon operator can be used to specify interactions between observed variables (e.g., `x11:y3` is the product between `x11` and `y3`), but not involving latent variables.

> how would you use simsem to generate the dataset used in these three articles?

You would have to write your own custom data-generating function in order to sample factor scores (and residuals), calculate factor scores from the latent outcome from the regression model, then calculate observed variables by summing factor scores and residuals (weighted by the item parameters).  See an example I posted on the lavaan forum:

https://groups.google.com/d/msg/lavaan/PxFUKcIwPd0/-T67JNWL4doJ

**Comment by N34980** [comment]
Thank you VERY much!
