### ISSUE TITLE
typo in labelling of SEM diagram 

### ISSUE THREAD

**Issue by oscci** [simsem/simsem#67]
I think F2 in lowest factor needs changing to F3 in the diagram for the initial simsem example for lavaan.
Many thanks for the very clear and comprehensive documentation for simsem. Working my through steadily.

**Comment by TDJorgensen** [comment]
Wow, it's been like that for so long!  Thanks for noticing :-)  [Fixed now](https://github.com/simsem/simsem/wiki/Example-2:-Covariance-Matrix-Specification), although I couldn't get the new pics to save in as high quality.  They were created years ago in Word with Shapes, instead of a nice reproducible program like TikZ in LaTeX.  One day I might have time to update that...
