### ISSUE TITLE
ImposeMissing function 

### ISSUE THREAD

**Issue by Nikazahe** [simsem/simsem#71]
Hi

I want to use the imposeMissing function to impose MAR (missing at random) values at specific timepoints of my dataset. I noticed that the values listed in the first item of the "list" for the itemGroups are ignored. For example, the code below does not result in missing values for timepoints 1, 2, and 3. It results in missing values for columns 7,8,9 for the full dataset. It is as if the first item of the list ie c(1,2,3) is ignored. 

**imposeMissing(data, nforms = 1, itemGroups = list(c(1,2,3), c(7,8,9)))**

So I'm wondering what the purpose of that first item is. I tried this as well and it still works the same way: 

**imposeMissing(data, nforms = 1, itemGroups =  list(c(), c(7,8,9)))**
                               

Do you know what the purpose of that first list item is? Thanks a lot in advance.

**Comment by TDJorgensen** [comment]
> It is as if the first item of the list ie c(1,2,3) is ignored.

Right, read the **Details** section of the help page more carefully:

> The first list of column indices given will be used as the shared group. If this is not desired, this list can be left empty.

The shared group of items have no missing data (i.e., everyone completes those items).  That is the "shared form" referred to in the description of the `nforms=` argument.

Instead of forms, you have occasions, so you need to specify the number of occasions for the `nforms=` argument and use the `itemGroups=` argument to assign column numbers corresponding to variables at those time points.

> I want to use the imposeMissing function to impose MAR (missing at random) values at specific timepoints of my dataset.

But I'm not sure you can do this with the planned-missing features, which impose MCAR data in blocks depending on the number of forms.  If you want attrition (missing on all variables for a timepoint), see the `prAttr=` argument.  For more flexibility in designing MAR mechanisms per item, I would write a script to use the `logit=' argument (see the final example on the help page).
