### ISSUE TITLE
Generating non-normal data using lavaan syntax style

### ISSUE THREAD

**Issue by iwoasned** [simsem/simsem#76]
Hi,

I tried to generate non-normal data using the code of Example 12 in lavaan style syntax (see below).

However, data generation produces multiple warnings and the data do not approach the specified non-normal distributions.

The warnings are as follows:
```
Warnings:
1: In nlminb(start = c(1, 0, 0), objective = system.function,  ... :
  NA/NaN function evaluation
2: In nlminb(start = c(1, 0, 0), objective = system.function,  ... :
  NA/NaN function evaluation
3: In nlminb(start = c(1, 0, 0), objective = system.function,  ... :
  NA/NaN function evaluation
4: In nlminb(start = c(1, 0, 0), objective = system.function,  ... :
  NA/NaN function evaluation
5: In nlminb(start = c(1, 0, 0), objective = system.function,  ... :
  NA/NaN function evaluation
6: In nlminb(start = c(1, 0, 0), objective = system.function,  ... :
  NA/NaN function evaluation
7: In fleishman1978_abcd(skewness = SK[i], kurtosis = KU[i]) :
  lavaan WARNING: ValeMaurelli1983 method did not convergence, or it did not find the roots

... warnings continue...
```
I run into the same problem when using different population models or specifying different non-normal distributions.

Do you have any idea how I can solve these problems? Thank you!

```
library(simsem)

popModel <- "
f1 =~ 0.7*y1 + 0.7*y2 + 0.7*y3 + 0.7*y4
f2 =~ 0.7*y5 + 0.7*y6 + 0.7*y7 + 0.7*y8
f3 =~ 0.7*y9 + 0.7*y10 + 0.7*y11 + 0.7*y12
f1 ~~ 1*f1
f2 ~~ 1*f2
f3 ~~ 1*f3
f1 ~~ 0.5*f2
f1 ~~ 0.5*f3
f2 ~~ 0.5*f3
y1 ~~ 0.51*y1
y2 ~~ 0.51*y2
y3 ~~ 0.51*y3
y4 ~~ 0.51*y4
y5 ~~ 0.51*y5
y6 ~~ 0.51*y6
y7 ~~ 0.51*y7
y8 ~~ 0.51*y8
y9 ~~ 0.51*y9
y10 ~~ 0.51*y10
y11 ~~ 0.51*y11
y12 ~~ 0.51*y12
f1 ~ 1*1
f2 ~ 2*1
f3 ~ 3*1
y1 ~ 0.5*1
y2 ~ 0.4*1
y3 ~ 0.3*1
y4 ~ 0.2*1
y5 ~ 0.1*1
y6 ~ 0*1
y7 ~ 0.1*1
y8 ~ 0.2*1
y9 ~ 0.3*1
y10 ~ 0.4*1
y11 ~ 0.5*1
y12 ~ 0.6*1
"

analyzeModel <- "
f1 =~ y1 + y2 + y3 + y4
f2 =~ y5 + y6 + y7 + y8
f3 =~ y9 + y10 + y11 + y12
"

distname <- c(rep("t", 4), rep("chisq", 8))

d1 <- list(df=2)
d2 <- list(df=3)
d3 <- list(df=4)
d4 <- list(df=5)
d5 <- list(df=3)
d6 <- list(df=4)
d7 <- list(df=5)
d8 <- list(df=6)
d9 <- list(df=3)
d10 <- list(df=4)
d11 <- list(df=5)
d12 <- list(df=6)

dist <- bindDist(distname, d1, d2, d3, d4, d5, d6, d7, d8, d9, d10, d11, d12, reverse=c(rep(FALSE, 8), rep(TRUE, 4)))

dat <- generate(model = popModel, n = 500, indDist = dist)

Output <- sim(10, n=200, analyzeModel, indDist=dist, generate=popModel, estimator="mlm", std.lv=TRUE, lavaanfun="cfa")
```

**Comment by TDJorgensen** [comment]
> `lavaan WARNING: ValeMaurelli1983 method did not convergence, or it did not find the roots`

If a solution cannot be found, then the combination of marginals probably couldn't actually coexist with your model-implied covariance structure.  Or at least, their algorithm cannot be used to find a transformation to yield that joint distribution. 

> how I can solve these problems? 

You could try different approaches with the `copula=` argument.  If nothing works, you could try the highly flexible but computationally intensive VITA method applied in the `covSim` package (see their vignette for description, references, and examples).  That newer method is not integrated into `simsem`, but you could certainly use it to generate a list of `data.frame`s, which you can then pass to `sim(..., rawData=)`.

**Comment by iwoasned** [comment]
Thanks so much for the quick response!

But might it be possible that there is an additional problem when using lavaan syntax style to generate non-normal data? If I specify the same model and marginals using the lavaan style versus the matrix style, the former produces problemes whereas the latter approach work fine. 

For instance:

```

library(simsem)


# lavaan Syntax specification ----------------------------------------------------

populationModel <- '

  g =~ .66*x1 + .57*x2 + .59*x3 + .60*x4 + .55*x5 + .65*x6 + .53*x7 + .58*x8 + .70*x9
  s1 =~ .44*x1 + .47*x2 + .43*x3
  s2 =~ .40*x4 + .30*x5 + .34*x6
  s3 =~ .32*x7 + .46*x8 + .40*x9
  x1 ~~ .3708*x1
  x2 ~~ .4542*x2
  x3 ~~ .4670*x3
  x4 ~~ .4800*x4
  x5 ~~ .6075*x5
  x6 ~~ .4619*x6
  x7 ~~ .6167*x7
  x8 ~~ .4520*x8
  x9 ~~ .35*x9
  g ~~ 1*g
  s1 ~~ 1*s1
  s2 ~~ 1*s2
  s3 ~~ 1*s3
  s1 + s2 + s3 ~~ 0*g
  s1 + s2 ~~ 0*s3
  s1 ~~ 0*s2
'

analysisModel <- '
  g =~ NA*x1 + x2 + x3 + x4 + x5 + x6 + x7 + x8 + x9
  s1 =~ NA*x1 + x2 + x3
  s2 =~ NA*x4 + x5 + x6
  s3 =~ NA*x7 + x8 + x9
  s1 + s2 + s3 ~~ 0*g
  s1 + s2 ~~ 0*s3
  s1 ~~ 0*s2
  g ~~ 1*g
  s1 ~~ 1*s1
  s2 ~~ 1*s2
  s3 ~~ 1*s3
'


dist <- bindDist(skewness = 2, kurtosis = 3, p = 9) 
data <- generate(model = populationModel, n = 500, indDist = dist)
Output <- sim(n = 500, generate=populationModel, model = analysisModel, lavaanfun = "cfa", nRep = 5, indDist = dist)
# => does not work

dist <- bindDist(skewness = -3, kurtosis = 10, p = 9) 
data <- generate(model = populationModel, n = 500, indDist = dist)
Output <- sim(n = 500, generate=populationModel, model = analysisModel, lavaanfun = "cfa", nRep = 5, indDist = dist)
# => does not work


# Matrix Specification ----------------------------------------------------

loadingValues <- matrix(0, nrow = 9, ncol = 4)
loadingValues[, 1] <- c(.66, .57, .59, .60, .55, .65, .53, .58, .70)
loadingValues[1:3, 2] <- c(.44, .47, .43)
loadingValues[4:6, 3] <- c(.40, .30, .34)
loadingValues[7:9, 4] <- c(.32, .46, .40)

loading <- loadingValues
loading[loading != 0] <- NA
LY <- bind(loading, loadingValues)

error.cor <- matrix(0, 9, 9)
diag(error.cor) <- 1 
RTE <- binds(error.cor)

latent.cor <- matrix(0, 4, 4)
diag(latent.cor) <- 1 
RPS <- binds(latent.cor)


bifactorModel <- model.cfa(LY = LY, RTE = RTE, RPS = RPS)

dist <- bindDist(skewness = 2, kurtosis = 3, p = 9) 
data <- generate(model = bifactorModel, n = 500, indDist = dist)
Output <- sim(n = 500, model = bifactorModel, nRep = 5, indDist = dist)
# => works

dist <- bindDist(skewness = -3, kurtosis = 10, p = 9) 
data <- generate(model = bifactorModel, n = 500, indDist = dist)
Output <- sim(n = 500, model = bifactorModel, nRep = 5, indDist = dist)
# => works



```

**Comment by TDJorgensen** [comment]
Here you are just specifying the skew and kurtosis, not the specific marginal distributions from your OP.  Does your original example "work" using the `SimMatrix` approach?

As the `?generate` help page states, simply specifying `skewness= , kurtosis=` will pass your lavaan model syntax to `lavaan::simulateData()`, which generates the warning messages you are seeing:
```
simulateData(populationModel, sample.nobs = 500, skewness = 2, kurtosis = 3)
simulateData(populationModel, sample.nobs = 500, skewness = -3, kurtosis = 10)
```

By the way, those are not error messages.  You still get data:
```
head(data)
```
But the marginal moments probably don't match your requests because (as the warnings state) a solution using that method could not locate a matching power-transformation.  Also, even if you set the same seed, you will not get the same results.  This is because `lavaan` uses `MASS::mvrnorm()`, whereas `simsem` uses an adjusted version of that function to populate random values `byrow=TRUE`, so that increasing `n=` will result in generating the same sampled rows but simply add more of them (see also `?rockchalk::mvrnorm`).

Now, onto the issue of warning messages.  This took a half hour for me to track down why the same warning message is not printed when using `SimMatrix` specification.

When you use a `SimMatrix` model representation, `generate()` passes `skewness= , kurtosis=` to `simsem::createData()`, which employs code that Sunthud borrowed from (and made modifications to) `lavaan::simulateData()`.  First, it does not write the same warning messages (compare [this line](https://github.com/yrosseel/lavaan/blob/master/R/lav_simulate_old.R#L395) from `lavaan` to [this line](https://github.com/simsem/simsem/blob/master/simsem/R/generate.R#L321) from `simsem`), but I still expected to see the (shorter) warning.  Then I noticed that `simsem` prints the warning ONLY when `nlminb()` indicates no `$convergence` with a code of 0, whereas `lavaan` will additionally print the warning when the `$objective` (minimum convergence criterion) exceeds .00001

So there you go.  You get data either way in the examples above (even in your OP), but `simsem` is less likely to warn you about a convergence problem, probably because the Vale-Maurelli algorithm would so frequently return a long list of warnings (per variable and per replication) that it would swamp other more-informative warnings about other issues that can occur in `sim()`.

This isn't really an issue with `simsem`, so I'm closing this.  

And I would recommend using a more robust method to generate nonnormal data, as Foldnes & Grønnenberg have been showing these past 5 years in numerous papers that the Vale-Maurelli is seriously flawed.  They are the authors of the `covSim` package that I recommended above.
